name: Feature request
description: Submit a new feature request
title: "[Feature Request]: "
labels: [enhancement]
assignees:
  - UlysseGuyon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: expected-behavior
    attributes:
      label: What would be the expected behavior of the new feature?
      placeholder: The package would do ...
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: What is the current behavior?
      description: You can leave this field empty if the new feature has nothing to do with existing ones
      placeholder: The package behaves as ...
    validations:
      required: false
  - type: textarea
    id: use-cases
    attributes:
      label: Please describe some motivations or use cases to implement this feature
      placeholder: The feature would allow the user to ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about this new feature!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false