name: CI

on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - run: go test ./tests